[repository]
name = "hycov"
authors = ["DreamMaoMao"]
commit_pins = [
	["03ebbe18ed8517ee22591eac82cd54322f42cb7d", "8ebefe07ba33bde673bb6644a0b1e53e5888882f"]
]

[hycov]
description = "hyprland overview mode"
authors = ["DreamMaoMao"]
output = "build/libhycov.so"
build = [
	"cmake -DCMAKE_BUILD_TYPE=Release -B build",
	"cmake --build build"
]