[repository]
name = "hycov"
authors = ["DreamMaoMao"]
commit_pins = [
	["03ebbe18ed8517ee22591eac82cd54322f42cb7d", "41a80fc01a4c2fca400e53e5d3b6ea81fa461822"]
]

[hycov]
description = "hyprland overview mode"
authors = ["DreamMaoMao"]
output = "build/libhycov.so"
build = [
	"cmake -DCMAKE_BUILD_TYPE=Release -B build",
	"cmake --build build"
]