[repository]
name = "hycov"
authors = ["DreamMaoMao"]
commit_pins = [
	["03ebbe18ed8517ee22591eac82cd54322f42cb7d", "0f1e52fd7e1235e870ca366d6e9219d0dda3f5bb"]
]

[hycov]
description = "hyprland overview mode"
authors = ["DreamMaoMao"]
output = "build/libhycov.so"
build = [
	"cmake -DCMAKE_BUILD_TYPE=Release -B build",
	"cmake --build build"
]